Update auto-deploy.yml

diff --git a/.github/workflows/auto-deploy.yml b/.github/workflows/auto-deploy.yml
--- a/.github/workflows/auto-deploy.yml
+++ b/.github/workflows/auto-deploy.yml
@@ -11,18 +11,14 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-
       - name: Set up .NET SDK
         uses: actions/setup-dotnet@v3
         with:
           dotnet-version: '8.0'
-
       - name: Restore dependencies
         run: dotnet restore
-
       - name: Build the project
         run: dotnet build --configuration Release
-
       - name: Run tests
         run: dotnet test
 
@@ -32,12 +28,10 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-        
       - name: Set up SSH agent
         uses: webfactory/ssh-agent@v0.5.3
         with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-
       - name: Deploy to remote server via SSH
         run: |
-          ssh -o StrictHostKeyChecking=no root@5.75.148.60 "cd /var/www/pentasharp && git pull && systemctl restart pentasharp.service"
+          ssh -o StrictHostKeyChecking=no root@5.75.148.60 "cd /var/www/pentasharp && git pull && systemctl restart pentasharp.service || { echo 'Deployment failed'; exit 1; }"
